import type { UnitDefinition } from "./types";

export const unitDefinitions: UnitDefinition[] = [
	{ name: "Cup", value: "cup", plural: "Cups" },
	{ name: "Tablespoon", value: "tbsp", plural: "Tablespoons" },
	{ name: "Teaspoon", value: "tsp", plural: "Teaspoons" },
	{ name: "Fluid Ounce", value: "fl oz", plural: "Fluid Ounces" },
	{ name: "Ounce", value: "oz", plural: "Ounces" },
	{ name: "Pound", value: "lb", plural: "Pounds" },
	{ name: "Gram", value: "g", plural: "Grams" },
	{ name: "Kilogram", value: "kg", plural: "Kilograms" },
	{ name: "Milliliter", value: "ml", plural: "Milliliters" },
	{ name: "Liter", value: "l", plural: "Liters" },
	{ name: "Pint", value: "pt", plural: "Pints" },
	{ name: "Quart", value: "qt", plural: "Quarts" },
	{ name: "Gallon", value: "gal", plural: "Gallons" },
	{ name: "Pinch", value: "pinch", plural: "Pinches" },
	{ name: "Dash", value: "dash", plural: "Dashes" },
	{ name: "Can", value: "can", plural: "Cans" },
	{ name: "Package", value: "pkg", plural: "Packages" },
	{ name: "Box", value: "box", plural: "Boxes" },
	{ name: "Bunch", value: "bunch", plural: "Bunches" },
	{ name: "Clove", value: "clove", plural: "Cloves" },
	{ name: "Head", value: "head", plural: "Heads" },
	{ name: "Stalk", value: "stalk", plural: "Stalks" },
	{ name: "Slice", value: "slice", plural: "Slices" },
	{ name: "Piece", value: "piece", plural: "Pieces" },
	{ name: "Whole", value: "whole", plural: "Wholes" },
	{ name: "Half", value: "half", plural: "Halves" },
	{ name: "Quarter", value: "quarter", plural: "Quarters" },
	{ name: "Dozen", value: "doz", plural: "Dozens" },
	{ name: "Handful", value: "handful", plural: "Handfuls" },
	{ name: "Sprig", value: "sprig", plural: "Sprigs" },
	{ name: "Leaf", value: "leaf", plural: "Leaves" },
	{ name: "Strip", value: "strip", plural: "Strips" },
	{ name: "Unit", value: "unit", plural: "Units" },
	{ name: "To Taste", value: "to taste", plural: "To Taste" },
	{ name: "As Needed", value: "as needed", plural: "As Needed" },
];

export const unitLessIngredients = [
	{ name: "To Taste", value: "to taste", plural: "To Taste" },
	{ name: "As Needed", value: "as needed", plural: "As Needed" },
];
